### ISSUE TITLE
Problem with installing Daisykit package on Windows

### ISSUE THREAD

**Issue by Malgorzatta** [nrl-ai/daisykit#29]
I’m trying to install daisykit package for Python but constantly facing the error  TypeError: CCompiler_spawn() got an unexpected keyword argument 'env' [end of output]
Could you help me with that? I work on Windows machine and I have installed Python 3.11 and all packages are upgraded.

**Comment by vietanhdev** [comment]
Could you please try Python 3.8?
Looking to your feedback.

**Comment by Malgorzatta** [comment]
Yes, now it works. Thanks!

**Comment by Malgorzatta** [comment]
@vietanhdev I also have a question - does daisykit work only on Windows and Linux? What about Mac?

**Comment by vietanhdev** [comment]
I tested it on mac m1 too. It can work on 3 OSes.
