### ISSUE TITLE
Barcode detection daisy kit error on MacOS

### ISSUE THREAD

**Issue by abhay-iy97** [nrl-ai/daisykit#30]
**Describe the bug**
Hi, I installed daisy kit and attempted to run the sample source code provided [here](https://daisykit.nrl.ai/docs/python/barcode) but I'm facing an error when I run the program. Thank you for your help.

**To Reproduce**
```
conda create -n myEnv python=3.8
pip install daisy kit
Run the source code
```

**Expected behavior**
Expected the code to open a window to capture camera feed for barcode detection

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: MacOS Ventura 13.4 (M2 MacBook Air)

**Smartphone (please complete the following information):**
NA

**Additional context**
Error:
```Traceback (most recent call last):
  File "/Users/aiyer/Desktop/test/barcode-daisy.py", line 3, in <module>
    from daisykit.utils import get_asset_file
  File "/Users/aiyer/anaconda3/envs/barcode-daisy/lib/python3.8/site-packages/daisykit/__init__.py", line 1, in <module>
    from .daisykit import *
ImportError: dlopen(/Users/aiyer/anaconda3/envs/barcode-daisy/lib/python3.8/site-packages/daisykit/daisykit.cpython-38-darwin.so, 0x0002): Library not loaded: /opt/homebrew/opt/opencv/lib/libopencv_gapi.407.dylib
  Referenced from: <AEBB01BC-AA4F-39BE-A928-846FBCC761E8> /Users/aiyer/anaconda3/envs/barcode-daisy/lib/python3.8/site-packages/daisykit/daisykit.cpython-38-darwin.so
  Reason: tried: '/opt/homebrew/opt/opencv/lib/libopencv_gapi.407.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/opt/opencv/lib/libopencv_gapi.407.dylib' (no such file), '/opt/homebrew/opt/opencv/lib/libopencv_gapi.407.dylib' (no such file), '/usr/local/lib/libopencv_gapi.407.dylib' (no such file), '/usr/lib/libopencv_gapi.407.dylib' (no such file, not in dyld cache)
  ```

**Comment by abhay-iy97** [comment]
Resolved this issue - unrelated to DaisyKit. 
It looks for an opencv installation in homebrew and not in conda virtual env.

```brew install opencv``` resolved it.

**Comment by vietanhdev** [comment]
@abhay-iy97  From version 0.3.0.2 you can run Daisykit without `brew install opencv`.
Please check if you have time:
```
pip install daisykit==0.3.0.2
```

Thank you very much for your bug report!

**Comment by abhay-iy97** [comment]
@vietanhdev Interesting, great to know. My current version of daisykit is 0.3.0.1
